apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotContent
metadata:
  name: backend-content
spec:
  deletionPolicy: Delete
  driver: pure-csi
  source:
    # TODO: change this to your backend snapshot name.
    # Make sure to put the full name here. 
    snapshotHandle: test-backend-vol.test-backend-snapshot
  volumeSnapshotRef:
    # TODO: Put your own snapshot object name here.
    # Make sure it's identical with the name in "backendsnapshot.yaml"
    name: backend-snapshot
    namespace: default
