apiVersion: v1
kind: Pod
metadata:
  name: nginx-0
spec:
  # Specify a volume that uses the restored claim
  volumes:
  - name: pure-vol-0
    persistentVolumeClaim:
      claimName: pvc-restore
  containers:
  - name: nginx-0
    image: nginx
    # Configure a mount for the volume We define above
    volumeMounts:
    - name: pure-vol-0
      mountPath: /data
    ports:
    - containerPort: 80
